---
title: "Sequence Variatonal Autoencoders"
output: html_notebook
---

```{r setup}
knitr::opts_knit$set(root.dir = '/home/harpo/hostdir/ia-dojo-repo/experiments/dga-gen/')
```

```{r message=FALSE, warning=FALSE}
library(keras)
library(tensorflow)
```


```{r}
source("code/R/functions/dgagen-helpers.R")
```
# Read domains
```{r}
library(urltools)
gc()
text <- readr::read_csv("rawdata/argencon.csv.gz")
text<-text %>% filter(grepl("normal",label))
text<-text %>% sample_frac(0.1)
domains <-  text %>% pull(domain)
domains <- domains %>% urltools::host_extract()
domains <- domains  %>% tidyr::drop_na() %>% pull(host)
```

```{r}
sentences_tokenized<-tokenize(domains %>% as.matrix, "n",maxlen)
shape <- c(nrow(sentences_tokenized$x), maxlen, length(valid_characters_vector))
seq_x<-to_onehot(sentences_tokenized$x,shape)
seq_x[1,,]
```

## Check one_hot
```{r}
dimen<-seq_x %>% dim()
enc<-""
for (i in 0:dimen[2]  ){
#      print(i)
      enc<-str_c(enc,valid_characters_vector[which.max(seq_x[1,i,])])
}
enc
```
 
```{r}
dim (seq_x)
```


## LSTM sequence Autoencoder

```{r}

input_size <-  c(maxlen, length(valid_characters_vector))
latent_dim <- 64 
## ENCODER
enc_input <- layer_input(shape = input_size) 
enc_output <- enc_input %>% 
  layer_masking(mask_value = 0) %>%
  layer_lstm(latent_dim)

## DECODER
dec_input <- layer_input(shape = latent_dim)
dec_output <-   dec_input %>% 
                layer_repeat_vector(maxlen) %>%
                layer_lstm(valid_characters_vector %>% length(), return_sequences = TRUE) %>%
                layer_dense(valid_characters_vector %>% length(),activation = 'softmax')
               #$ outputs = TimeDistributed(Dense(vocab_size, activation='softmax'))(decoder1)
  
encoder <- keras_model(enc_input, enc_output,name ="encoder")
decoder <- keras_model(dec_input, dec_output,name ="decoder")

encoder
decoder
```


```{r}

autoencoder_input <- layer_input(shape = input_size,name="ae_input")
autoencoder_output <- autoencoder_input %>% 
  encoder() %>% 
  decoder()
autoencoder <- keras_model(autoencoder_input, autoencoder_output,name="autoencoder")
optimizer <- optimizer_adam(learning_rate = 0.005)
autoencoder %>% compile(optimizer= optimizer, loss='mse')
autoencoder
```
 
```{r}
autoencoder %>% fit(seq_x, seq_x,
                epochs=15,
                batch_size=512)
```
```{r}
save_model_tf(decoder,"../../../models/dgagen-decoder.keras")
```
 
```{r}
decoder_b <- load_model_tf("../../../models/dgagen-decoder.keras")
```


## VAE

### Encoder
##### CNN
```{r}

latent_dim <- 2
input_size <-  c(maxlen, length(valid_characters_vector))
encoder_inputs <-  layer_input(shape=input_size)

x <- encoder_inputs %>%
   layer_masking(mask_value = 0) %>%
  layer_conv_1d(32, 3, activation = "relu", strides = 2, padding = "same") %>%
  layer_conv_1d(64, 3, activation = "relu", strides = 2, padding = "same") %>%
  layer_flatten() %>%
  layer_dense(16, activation = "relu")
z_mean    <- x %>% layer_dense(latent_dim, name="z_mean")
z_log_var <- x %>% layer_dense(latent_dim, name="z_log_var")
encoder <- keras_model(encoder_inputs, list(z_mean, z_log_var),
                       name="encoder")
```

#### LSTM
```{r}
latent_dim <- 128
input_size <-  c(maxlen, length(valid_characters_vector))
encoder_inputs <-  layer_input(shape=input_size)

x <- encoder_inputs %>%  
  layer_masking(mask_value = 0) %>%
  layer_lstm(256, return_sequences = TRUE) %>%
  layer_lstm(128)

z_mean    <- x %>% layer_dense(latent_dim, name="z_mean")
z_log_var <- x %>% layer_dense(latent_dim, name="z_log_var")
encoder <- keras_model(encoder_inputs, list(z_mean, z_log_var),
                       name="encoder")

```



```{r}
encoder
```


### Sampler

```{r}
layer_sampler <- new_layer_class(
  classname = "Sampler",
  call = function(self, z_mean, z_log_var) {
    epsilon <- tf$random$normal(shape = tf$shape(z_mean),mean=0., stddev=1.0 )
    z_mean + exp(0.5 * z_log_var) * epsilon
  }
)
```


### Decoder
#### CNN

```{r}
latent_inputs <- layer_input(shape = c(latent_dim))
decoder_outputs <- latent_inputs %>%
  layer_dense(10 * 64, activation = "relu") %>%
  layer_reshape(c(10, 64)) %>%
  layer_conv_1d_transpose(64, 3, activation = "relu",
                          strides = 2, padding = "same") %>%
  layer_conv_1d_transpose(32, 3, activation = "relu",
                          strides = 2, padding = "same") %>%
  layer_conv_1d(44, 3, activation = "sigmoid", padding = "same")
decoder <- keras_model(latent_inputs, decoder_outputs,
                       name = "decoder")
```
#### LSTM
```{r}
latent_inputs <- layer_input(shape = c(latent_dim))
decoder_outputs <- latent_inputs %>% 
 # layer_dense(256, activation = 'relu') %>%
  layer_repeat_vector(maxlen) %>%
  layer_lstm(64, return_sequences = TRUE) %>%
  layer_lstm(128, return_sequences = TRUE) %>%
  layer_dense(valid_characters_vector %>% length(),activation = 'softmax')
decoder <- keras_model(latent_inputs, decoder_outputs,
                       name = "decoder")
```

```{r}
decoder
```


### Model
```{r}
model_vae <- new_model_class(
  classname = "VAE",

  initialize = function(encoder, decoder, ...) {
    super$initialize(...)
    self$encoder <- encoder
    self$decoder <- decoder
    self$sampler <- layer_sampler()
    self$total_loss_tracker <-
      metric_mean(name = "total_loss")
    self$reconstruction_loss_tracker <-
      metric_mean(name = "reconstruction_loss")
    self$kl_loss_tracker <-
      metric_mean(name = "kl_loss")
  },

  metrics = mark_active(function() {
    list(
      self$total_loss_tracker,
      self$reconstruction_loss_tracker,
      self$kl_loss_tracker
    )
  }),

  train_step = function(data) {
    with(tf$GradientTape() %as% tape, {

      c(z_mean, z_log_var) %<-% self$encoder(data)
      z <- self$sampler(z_mean, z_log_var)

      
      mask <- k_cast(k_not_equal(data, 0), dtype='float32')
      reconstruction <- decoder(z)  * mask     
     # reconstruction <- k_cast(reconstruction,dtpye='float32')
     # reconstruction_loss <- 
     #   loss_binary_crossentropy(data, reconstruction) %>%
     #      sum(axis = c(2)) %>%
     #       mean()

      reconstruction_loss <-  k_binary_crossentropy(data, reconstruction) # %>% mean()
      reconstruction_loss <- sum (reconstruction_loss, axis = -1 ) #%>% mean()
      kl_loss <- -0.5 * (1 + z_log_var - z_mean^2 - exp(z_log_var))
      kl_loss <- sum(kl_loss) #%>% mean()
      total_loss <- mean( reconstruction_loss + kl_loss)
    })

    grads <- tape$gradient(total_loss, self$trainable_weights)
    self$optimizer$apply_gradients(zip_lists(grads, self$trainable_weights))

    self$total_loss_tracker$update_state(total_loss)
    self$reconstruction_loss_tracker$update_state(reconstruction_loss)
    self$kl_loss_tracker$update_state(kl_loss)

    list(total_loss = self$total_loss_tracker$result(),
         reconstruction_loss = self$reconstruction_loss_tracker$result(),
         kl_loss = self$kl_loss_tracker$result())
  }
)
```



```{r}
 mask <- k_not_equal(vectorized_test, 0)
tf$boolean_mask(vectorized_test,mask)
```


```{r}
mask <- k_cast(k_not_equal(vectorized_test, 0), dtype='float64')
mask * decoded[1,,]

loss_mean_absolute_error(vectorized_test,decoded[1,,]) %>% sum(axis=c(2))

loss_binary_crossentropy(vectorized_test,vectorized_test) 

dim(decoded)
dim(vectorized_test)

```


# Training
```{r}
vae <- model_vae(encoder, decoder)
vae %>% compile(optimizer = optimizer_adam())


## -------------------------------------------------------------------------
#vae %>% fit(mnist_digits, epochs = 30, batch_size = 128)
vae %>% fit(seq_x,epochs=3,
                batch_size=512)


```

```{r}

```


```{r}
library(lubridate)
#autoencoder$get_layer("decoder") %>% get_weights()

d<-domains[1]

mdate<-( lubridate::now() + lubridate::days(2) ) %>% as.character()  %>% gsub(x=.,"[:-]","")

mdate<-(now() %>% as.integer())
d<-paste0(mdate)
d
```


```{r}
d<-domains[1]
print(d)
vectorized_test <- tokenize(d, "n", maxlen)
      shape = c(nrow(vectorized_test$x),
                maxlen,
                length(valid_characters_vector))
vectorized_test <- to_onehot(vectorized_test$x, shape)
dim(vectorized_test)
preds_encoder <- vae$encoder(vectorized_test)
#preds_encoder

decoded <- predict(vae$decoder, preds_encoder[[1]])
dim(decoded)
enc<-""
for (i in 1:dimen[2]  ){
  enc<-str_c(enc,valid_characters_vector[which.max(decoded[1,i,])])
}
print(enc) 
#enc %>% gsub(x=. , "\\.(.{1,3}).*$",".\\1")


```


```{r}

z_grid <-
  seq(-1, 1, length.out = 10) %>%
  expand.grid(., .) %>%
  as.matrix()

decoded <- predict(vae$decoder, z_grid)
#decoded[3,,]
dim(decoded)

#dimen<- preds %>% dim()

dimen
for (j in 1:nrow(z_grid)){
  enc<-""
  for (i in 1:dimen[2]  ){
    enc<-str_c(enc,valid_characters_vector[which.max(decoded[j,i,])])
  }
  print(enc)
  #enc %>% gsub(x=. , "\\.(.{1,3}).*$",".\\1")
  
}
```
